package com.advs.train.dao;

import com.advs.train.model.ModelDSInfo;
import com.advs.train.model.ModelDSInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ModelDSInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table model_ds_info
	 * @mbg.generated  Mon Apr 19 00:55:29 PDT 2021
	 */
	long countByExample(ModelDSInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table model_ds_info
	 * @mbg.generated  Mon Apr 19 00:55:29 PDT 2021
	 */
	int deleteByExample(ModelDSInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table model_ds_info
	 * @mbg.generated  Mon Apr 19 00:55:29 PDT 2021
	 */
	int insert(ModelDSInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table model_ds_info
	 * @mbg.generated  Mon Apr 19 00:55:29 PDT 2021
	 */
	int insertSelective(ModelDSInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table model_ds_info
	 * @mbg.generated  Mon Apr 19 00:55:29 PDT 2021
	 */
	List<ModelDSInfo> selectByExample(ModelDSInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table model_ds_info
	 * @mbg.generated  Mon Apr 19 00:55:29 PDT 2021
	 */
	int updateByExampleSelective(@Param("record") ModelDSInfo record, @Param("example") ModelDSInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table model_ds_info
	 * @mbg.generated  Mon Apr 19 00:55:29 PDT 2021
	 */
	int updateByExample(@Param("record") ModelDSInfo record, @Param("example") ModelDSInfoExample example);

	List<ModelDSInfo> selectAll();
}