package com.advs.train.dao;

import com.advs.train.model.NERModelInfo;
import com.advs.train.model.NERModelInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface NERModelInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ner_model_info
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	long countByExample(NERModelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ner_model_info
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	int deleteByExample(NERModelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ner_model_info
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	int insert(NERModelInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ner_model_info
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	int insertSelective(NERModelInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ner_model_info
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	List<NERModelInfo> selectByExample(NERModelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ner_model_info
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	int updateByExampleSelective(@Param("record") NERModelInfo record, @Param("example") NERModelInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ner_model_info
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	int updateByExample(@Param("record") NERModelInfo record, @Param("example") NERModelInfoExample example);

	List<NERModelInfo> selectAll();
}