package com.advs.train.model;

import java.util.Date;

public class NERModelInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.id
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.name
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.location
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.version
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.create_date
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.create_user
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.config
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private String config;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.modified_date
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private Date modifiedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ner_model_info.modified_user
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	private String modifiedUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.id
	 * @return  the value of ner_model_info.id
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.id
	 * @param id  the value for ner_model_info.id
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.name
	 * @return  the value of ner_model_info.name
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.name
	 * @param name  the value for ner_model_info.name
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.location
	 * @return  the value of ner_model_info.location
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.location
	 * @param location  the value for ner_model_info.location
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setLocation(String location) {
		this.location = location == null ? null : location.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.version
	 * @return  the value of ner_model_info.version
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.version
	 * @param version  the value for ner_model_info.version
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.create_date
	 * @return  the value of ner_model_info.create_date
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.create_date
	 * @param createDate  the value for ner_model_info.create_date
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.create_user
	 * @return  the value of ner_model_info.create_user
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.create_user
	 * @param createUser  the value for ner_model_info.create_user
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.config
	 * @return  the value of ner_model_info.config
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public String getConfig() {
		return config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.config
	 * @param config  the value for ner_model_info.config
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setConfig(String config) {
		this.config = config == null ? null : config.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.modified_date
	 * @return  the value of ner_model_info.modified_date
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.modified_date
	 * @param modifiedDate  the value for ner_model_info.modified_date
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ner_model_info.modified_user
	 * @return  the value of ner_model_info.modified_user
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ner_model_info.modified_user
	 * @param modifiedUser  the value for ner_model_info.modified_user
	 * @mbg.generated  Mon Apr 19 17:27:41 PDT 2021
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
	}
}