server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml 
  type-aliases-package: com.example.model
  mapper-locations: classpath:mybatis/*Mapper.xml
  
spring:
  application:
    name: SprintbootRedis
  datasource:
    driver-class-name: org.postgresql.Driver
    username: tsdata
    password: milan123
    url: jdbc:postgresql://10.2.152.197:5432/tsdata
  redis:
    database: 0
    host : 127.0.0.1
    port: 6379
    password:
    pool:
      max-active:200
      max-wait:-1
      max-idle:10
      min-idle:0
    
logging:
  file: logs/server.log
    